apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-container
        image: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/next-development:latest
        ports:
        - containerPort: 3000
        imagePullSecrets:
        - name: ecr-secret 
      restartPolicy: Always
