apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs-app
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: nextjs-app
